config/routes.rb
Ipai100::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "shop_api/login"

  post "shop_api/publish"

  resources :messages do
    get :list, :on => :collection
  end

  get "home/index"

  get "syncs/index" => "syncs#index", :as => :sync_index
  match "syncs/destroy/:id" => "syncs#destroy", :as => :sync_destroy
#  get "syncs/callback"

  match "syncs/:type/new" => "syncs#new", :as => :sync_new
  match "syncs/:type/callback" => "syncs#callback", :as => :sync_callback

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "messages#list"

  match "users/update_info" => "users#update_info", :as => :update_info

  match "users/update_pwd" => "users#update_pwd", :as => :update_pwd
  resources :users




  resources :sessions
end

app/controllers/syncs_controller.rb
class SyncsController < ApplicationController

  def index

  end

  def destroy
    if params[:id]
      site = SyncSite.find(params[:id])
      site.destroy if site
    end

    redirect_to( sync_index_path)
  end

  def new
    user = current_user
    if user
      user.sync_sites.each do |site|
        if site.site_name == params[:type]
          redirect_to(sync_index_path, :notice => '同步设置已经存在!')
          return
        end
      end
    end
    client = OauthWrapper.get_oauth_obj(params[:type]).new
    authorize_url = client.authorize_url
    Rails.cache.write(build_oauth_token_key(client.name, client.oauth_token), client.dump)
    redirect_to authorize_url
  end

  def callback
    client =  OauthWrapper.get_oauth_obj(params[:type]).load(Rails.cache.read(build_oauth_token_key(params[:type], params[:oauth_token])))
    client.authorize(:oauth_verifier => params[:oauth_verifier])

    results = client.dump

    if results[:access_token] && results[:access_token_secret]
      site = SyncSite.new
      site.site_name = params[:type]
      site.token = results[:access_token]
      site.secret= results[:access_token_secret]
      site.user_id = session[:user_id]
      site.save!
      #在这里把access token and access token secret存到db
      #下次使用的时候:
      #client = OauthChina::Sina.load(:access_token => "xx", :access_token_secret => "xxx")
      #client.add_status("同步到新浪微薄..")
      flash[:notice] = "授权成功！"
    else
      flash[:notice] = "授权失败!"
    end
    redirect_to sync_index_path
  end

  private
  def build_oauth_token_key(name, oauth_token)
    [name, oauth_token].join("_")
  end

end

app/helpers/syncs_helper.rb
module SyncsHelper
end

app/views/syncs/callback.html.erb
<h1>Syncs#callback</h1>
<p>Find me in app/views/syncs/callback.html.erb</p>

app/views/syncs/index.html.erb
<h1>同步设置</h1>
<p><%=link_to "同步到新浪", sync_new_path(:type => "sina") %></p>
<p><%=link_to "同步到豆瓣", sync_new_path(:type => "douban") %></p>
<p><%=link_to "同步到QQ", sync_new_path(:type => "qq") %></p>
<p><%=link_to "同步到搜狐", sync_new_path(:type => "sohu") %></p>
<p><%=link_to "同步到网易", sync_new_path(:type => "netease") %></p>

<table>
<% if current_user %>
  <% current_user.sync_sites.each do |site| %>
    <tr>
     <td>  <%= site.site_name %></td>
      <td><%= button_to  '解除同步', { :controller => "syncs",
      :action => "destroy", :id => site.id }, :confirm => 'Are you sure?' %></td>
    </tr>
  <% end %>

<% end %>
</table>