config/routes.rb
Ipai100::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "shop_api/login"

  post "shop_api/publish"

  resources :messages do
    get :list, :on => :collection
  end

  get "home/index"

  get "syncs/index" => "syncs#index", :as => :sync_index
  match "syncs/destroy/:id" => "syncs#destroy", :as => :sync_destroy
#  get "syncs/callback"

  match "syncs/:type/new" => "syncs#new", :as => :sync_new
  match "syncs/:type/callback" => "syncs#callback", :as => :sync_callback

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "messages#list"

  match "users/update_info" => "users#update_info", :as => :update_info

  match "users/update_pwd" => "users#update_pwd", :as => :update_pwd
  resources :users




  resources :sessions
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :phone_no, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :phone_no
  validates_uniqueness_of :phone_no
  validates :phone_no, :length => 11..11
  validates :password, :length => 6..20
  validates :phone_no, :numericality  => true
  validates :password, :numericality  => true

  has_many :sync_sites, :dependent => :destroy
  has_many :messages, :dependent => :destroy

  belongs_to :user_info
  before_create :create_user_info

  def self.authenticate(phone_no, password)
    user = find_by_phone_no(phone_no)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  protected

  def create_user_info
    user_info = UserInfo.new
    user_info.save
    self.user_info_id = user_info.id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "注册!"
    else
      render "new"
    end
  end

  def update_info

    @user = current_user
    @user_info = @user.user_info

    if request.method == "POST"
      @user_info.nickname =  params[:user_info][:nickname]
      @user_info.description = params[:user_info][:description]
      @user_info.photo = params[:user_info][:photo] if params[:user_info][:photo]
      @message = "已保存！" if @user_info.save

    end

    render "info"

  end


  def update_pwd
    @user = current_user

    if request.method == "POST"

      if params[:password] == params[:password_confirmation]
        @user.password = params[:password]
        if @user.save
          @message = "更改密码成功！"
        end
      else
        @user.errors.add(:base, "两次密码输入不一致，请重新输入。")
      end

    end

    render "pwd"

  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/info.html.erb
<h1>个人信息</h1>

<%= form_for(:user_info,:url => {:action => 'update_info'}, :html => { :multipart => true } ) do |f| %>
  <% if @user_info.errors.any? %>
    <div class="error_messages">
      <ul>
        <% for message in @user_info.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

       <%if @message %>
        <p><%= @message %></p>
        <% end %>

  <p>
    <%= f.label :nickname, "昵称" %><br />
    <%= f.text_field :nickname %>
  </p>
  <p>
    <%= f.label :description, "个人简介" %><br />
    <%= f.text_area :description, :rows => 10, :cols => 60 %>
  </p>

    <br/>
    <% if @user_info.photo.present?  %>
        <%= image_tag(@user_info.photo.url(:original))%> <br/>
    <% end %>
        <%= f.label :photo, "更换头像" %>


    <%= f.file_field :photo %>

  <p class="button"><%= submit_tag "更改" %></p>
<% end %>

app/views/users/new.html.erb
<div id="signup-content"  class="signup-wrapper">
	<h1 class="signup-logo"> <a href="/" title="爱拍网"></a> </h1>
	<div class="signup-message_box">欢迎注册(或找回密码)，请输入11位手机号码，密码将被发送至您的手机！</div>
	<div id="signup_form" class="signup-action clearfix">

      <%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div class="error_messages">
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

        <div class="signup-item-wrapper">
        <%= f.text_field :phone_no, :class => 'signup-input', :id => 'phone_no' %>
        <%= f.label :phone_no, "手机号码", :class => 'signup-label'%>
        </div>

        <%= f.submit  "",  :class => 'signup-submit'%>

        <br/>

  <p>
    <%= f.label :password, "密码 （请输入6-20位数字作为密码）" %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "确认密码" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
       <% end %>
   </div>
</div>

app/views/users/pwd.html.erb
<h1>更改密码</h1>

<%= form_tag update_pwd_path do %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>



      </ul>
    </div>


  <% end %>
       <%if @message %>
        <p><%= @message %></p>
        <% end %>
  <p>
    <%= label_tag :password, "密码" %><br />
    <%= password_field_tag :password %>
  </p>
  <p>
    <%= label_tag :password_confirmation, "确认密码" %><br />
    <%= password_field_tag :password_confirmation %>
  </p>
  <p class="button"><%= submit_tag "更改密码" %></p>
<% end %>